# This is basis workflwo for nodejs, it will run on push and pull request on master branc
name: Channing the jobs with conditions
on:
  workflow_dispatch:
    inputs:
      run-job-3:
        description: "Run Job 3"
        required: true
        type: boolean

jobs:
  job-1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - name: Output of the job1
        run: echo "Hello input received from $ {{ github.event.inputs.run-job-3 }}"
      - name: Make job1 fail
        run: exit 1
  job-2:
    name: Job 2
    runs-on: ubuntu-latest
    needs:
      - job-1
    steps:
      - name: Output of the job 2
        run: echo "Hello from Job2"
  job-3:
    name: Job 3
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.run-job-3 == 'true' }}
    needs:
      - job-1
    steps:
      - name: Output of the job 3
        run: echo "Hello from Job3"
