name: Hello-World
on:
  push: 
    branches:
      - main
jobs:
  hello-world-print-job:
    runs-on: ubuntu-latest
    steps:
      - name: print hello world
        run: echo "hello-world first github actions"
