# This is basis workflwo for nodejs, it will run on push and pull request on master branc
name: Basic workflow with inputs and needs example.
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name of the person to greet"
        required: true
        default: "Mona the Octocat"
        type: string
      city:
        description: "City of the person to greet"
        required: true
        default: "San Francisco"
        type: choice
        options:
          - "San Francisco"
          - "Amsterdam"
          - "London"
          - "New York"
      fav-color-blue:
        description: "Is Blue your favorite color?"
        required: true
        type: boolean
jobs:
  job-1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - name: Output of the job1
        run: echo "Hello ${{ github.event.inputs.name }} from ${{ github.event.inputs.city }}"
  job-2:
    name: Job 2
    runs-on: ubuntu-latest
    needs:
      - job-1
    steps:
      - name: Output of the job 2
        run: echo "Hello from Job2"
  job-3:
    name: Job 3
    runs-on: ubuntu-latest
    needs:
      - job-1
    steps:
      - name: Output of the job 3
        run: echo "Hello from Job3"
